# -*- coding: utf-8 -*-
"""chatbot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YiJkqC64iDjudNiWvAC6PcP3Qq9ciYnm
"""

# ==============================
# STEP 1: Install Required Packages (if not already installed)
# ==============================
!pip install langchain langchain-core langgraph gradio pandas huggingface-hub chromadb sentence-transformers

# ==============================
# STEP 2: Import Libraries
# ==============================
import pandas as pd
import os
import gradio as gr
from typing import Annotated, TypedDict, Optional, List
from langchain_core.messages import BaseMessage, HumanMessage, SystemMessage, AIMessage
from langgraph.graph import StateGraph, START, END
from langgraph.graph.message import add_messages
from huggingface_hub import InferenceClient
from google.colab import userdata
import chromadb
from chromadb.utils import embedding_functions

# ==============================
# STEP 3: SETUP HUGGING FACE API
# ==============================
try:
    HF_TOKEN = userdata.get('HF_TOKEN')
    if HF_TOKEN:
        print("✅ Using HF_TOKEN from Colab secrets")
    else:
        raise ValueError("HF_TOKEN not found in secrets")
except:
    HF_TOKEN = input("Enter your Hugging Face token: ").strip()
    if not HF_TOKEN:
        raise ValueError("HF_TOKEN is required")

os.environ["HF_TOKEN"] = HF_TOKEN

# ==============================
# STEP 4: LOAD YOUR CSV FILES
# ==============================
from google.colab import files

print("\n📁 Please upload your hospital CSV file:")
uploaded_hospitals = files.upload()
hospital_filename = list(uploaded_hospitals.keys())[0]
hospitals_df = pd.read_csv(hospital_filename)

print("\n📁 Please upload your doctor CSV file:")
uploaded_doctors = files.upload()
doctor_filename = list(uploaded_doctors.keys())[0]
doctors_df = pd.read_csv(doctor_filename)

print(f"\n✅ Loaded {len(hospitals_df)} hospitals")
print(f"✅ Loaded {len(doctors_df)} doctors")

# ==============================
# STEP 5: SETUP VECTOR DATABASE
# ==============================
print("\n🔧 Setting up vector database...")

# Initialize ChromaDB
chroma_client = chromadb.Client()

# Use sentence-transformers for embeddings
sentence_transformer_ef = embedding_functions.SentenceTransformerEmbeddingFunction(
    model_name="all-MiniLM-L6-v2"
)

# Create or get collections
try:
    hospital_collection = chroma_client.get_collection(
        name="hospitals",
        embedding_function=sentence_transformer_ef
    )
    print("✅ Using existing hospital collection")
except:
    hospital_collection = chroma_client.create_collection(
        name="hospitals",
        embedding_function=sentence_transformer_ef
    )
    print("✅ Created new hospital collection")

try:
    doctor_collection = chroma_client.get_collection(
        name="doctors",
        embedding_function=sentence_transformer_ef
    )
    print("✅ Using existing doctor collection")
except:
    doctor_collection = chroma_client.create_collection(
        name="doctors",
        embedding_function=sentence_transformer_ef
    )
    print("✅ Created new doctor collection")

# Check if collections have data
if hospital_collection.count() == 0:
    print("📊 Adding hospitals to vector database...")
    hospital_docs = []
    hospital_metadata = []
    hospital_ids = []

    for idx, row in hospitals_df.iterrows():
        # Create bed info
        bed_info = []
        for col in ['ICU_Beds', 'General_Ward_Beds', 'NICU_Beds', 'Women_Ward_Beds', 'Deluxe_Ward_Beds']:
            if col in hospitals_df.columns and pd.notna(row.get(col)) and row.get(col, 0) > 0:
                bed_info.append(f"{col}: {row[col]} beds")

        # Create blood info
        blood_info = []
        for blood in ['A+', 'A-', 'B+', 'B-', 'AB+', 'AB-', 'O+', 'O-']:
            if blood in hospitals_df.columns and pd.notna(row.get(blood)) and row.get(blood, 0) > 0:
                blood_info.append(f"{blood}: {row[blood]} units")

        doc = f"""
Hospital: {row['Name']}
Address: {row['Address']}
Contact: {row['Contact']}

Available Beds:
{chr(10).join(bed_info) if bed_info else 'No beds currently available'}

Available Blood:
{chr(10).join(blood_info) if blood_info else 'No blood currently available'}

Specialties: {row.get('Available_Specialties', 'Not specified')}
"""
        hospital_docs.append(doc)
        hospital_metadata.append({
            "name": row['Name'],
            "address": row['Address'],
            "contact": row['Contact'],
            "type": "hospital"
        })
        hospital_ids.append(f"hospital_{idx}")

    hospital_collection.add(
        documents=hospital_docs,
        metadatas=hospital_metadata,
        ids=hospital_ids
    )
    print(f"✅ Added {len(hospital_docs)} hospitals")

if doctor_collection.count() == 0:
    print("📊 Adding doctors to vector database...")
    doctor_docs = []
    doctor_metadata = []
    doctor_ids = []

    for idx, row in doctors_df.iterrows():
        # Find hospital name
        hospital_name = "Unknown"
        if 'Hospital_ID' in row and pd.notna(row['Hospital_ID']):
            hospital_match = hospitals_df[hospitals_df['Hospital_ID'] == row['Hospital_ID']]
            if not hospital_match.empty:
                hospital_name = hospital_match.iloc[0]['Name']

        doctor_name = row.get('Name', row.get('Name_x', f'Dr. {idx}'))

        doc = f"""
Doctor: {doctor_name}
Specialty: {row['Specialty']}
Hospital: {hospital_name}
Status: {'Available' if row.get('Is_Available', False) else 'Not Available'}
On Call: {'Yes' if row.get('On_Call_Emergency', False) else 'No'}
Experience: {row.get('Experience_Years', 'Unknown')} years
"""
        doctor_docs.append(doc)
        doctor_metadata.append({
            "name": doctor_name,
            "specialty": row['Specialty'],
            "hospital": hospital_name,
            "available": bool(row.get('Is_Available', False)),
            "on_call": bool(row.get('On_Call_Emergency', False)),
            "experience": row.get('Experience_Years', 0),
            "type": "doctor"
        })
        doctor_ids.append(f"doctor_{idx}")

    doctor_collection.add(
        documents=doctor_docs,
        metadatas=doctor_metadata,
        ids=doctor_ids
    )
    print(f"✅ Added {len(doctor_docs)} doctors")

print(f"\n📊 Database stats: {hospital_collection.count()} hospitals, {doctor_collection.count()} doctors")

# ==============================
# STEP 6: HUGGING FACE LLM SETUP
# ==============================
class EmergencyDispatcherLLM:
    def __init__(self, model_id="microsoft/Phi-3-mini-4k-instruct", token=HF_TOKEN):
        self.client = InferenceClient(model=model_id, token=token)

    def generate_response(self, query, hospital_results, doctor_results):
        """Generate response using RAG results"""

        # Format hospital results
        hospital_text = "=== AVAILABLE HOSPITALS ===\n"
        if hospital_results and 'documents' in hospital_results and hospital_results['documents'][0]:
            for i, doc in enumerate(hospital_results['documents'][0]):
                metadata = hospital_results['metadatas'][0][i]
                hospital_text += f"\n🏥 {metadata['name']}\n"
                hospital_text += f"📍 {metadata['address']}\n"
                hospital_text += f"📞 {metadata['contact']}\n"
                # Extract key info from document
                doc_lines = doc.split('\n')
                for line in doc_lines:
                    if 'Beds:' in line or 'Blood:' in line or 'Specialties:' in line:
                        hospital_text += f"   {line.strip()}\n"
        else:
            hospital_text += "No matching hospitals found.\n"

        # Format doctor results
        doctor_text = "\n=== AVAILABLE DOCTORS ===\n"
        if doctor_results and 'documents' in doctor_results and doctor_results['documents'][0]:
            for i, doc in enumerate(doctor_results['documents'][0]):
                metadata = doctor_results['metadatas'][0][i]
                if metadata.get('available', False):  # Only show available doctors
                    doctor_text += f"\n👨‍⚕️ {metadata['name']}\n"
                    doctor_text += f"   Specialty: {metadata['specialty']}\n"
                    doctor_text += f"   Hospital: {metadata['hospital']}\n"
                    if metadata.get('experience'):
                        doctor_text += f"   Experience: {metadata['experience']} years\n"
        else:
            doctor_text += "No available doctors found.\n"

        # Create prompt for LLM
        prompt = f"""<|system|>
You are an Emergency Hospital Dispatcher AI. Your role is to help people find emergency medical services quickly and accurately.

Based on the search results below, provide a helpful response to the user's emergency query. Format your response clearly and include:
- Hospital names, addresses, and contact numbers
- Types of beds available
- Available doctors with their specialties
- Blood availability if relevant

Keep responses concise but include all critical information for an emergency.
and give only info about what they ask not other than this
<|end|>
<|user|>
Emergency Query: {query}

Search Results:
{hospital_text}
{doctor_text}
<|end|>
<|assistant|>"""

        try:
            response = self.client.text_generation(
                prompt,
                max_new_tokens=800,
                temperature=0.1,
                do_sample=True,
                return_full_text=False
            )
            return response
        except Exception as e:
            print(f"Error calling Hugging Face: {e}")
            return self._generate_fallback_response(hospital_text, doctor_text)

    def _generate_fallback_response(self, hospital_text, doctor_text):
        """Generate a simple response if LLM fails"""
        response = "Here are the available emergency resources I found:\n\n"
        response += hospital_text
        response += doctor_text
        return response

# Initialize LLM
llm = EmergencyDispatcherLLM()

# ==============================
# STEP 7: SEARCH FUNCTIONS
# ==============================
def search_hospitals(query: str, n_results: int = 5):
    """Search hospitals using semantic search"""
    try:
        results = hospital_collection.query(
            query_texts=[query],
            n_results=n_results
        )
        return results
    except Exception as e:
        print(f"Error searching hospitals: {e}")
        return None

def search_doctors(query: str, n_results: int = 5):
    """Search doctors using semantic search"""
    try:
        results = doctor_collection.query(
            query_texts=[query],
            n_results=n_results
        )
        return results
    except Exception as e:
        print(f"Error searching doctors: {e}")
        return None

def format_results_for_display(hospital_results, doctor_results):
    """Format search results for display"""
    output = []

    if hospital_results and hospital_results['documents'] and hospital_results['documents'][0]:
        output.append("🏥 **HOSPITALS WITH RESOURCES:**")
        for i, doc in enumerate(hospital_results['documents'][0][:3]):  # Show top 3
            metadata = hospital_results['metadatas'][0][i]
            output.append(f"\n**{metadata['name']}**")
            output.append(f"📍 {metadata['address']}")
            output.append(f"📞 {metadata['contact']}")

            # Extract bed info
            bed_lines = [line for line in doc.split('\n') if 'Beds:' in line]
            if bed_lines:
                output.append(f"🛏️ {bed_lines[0].strip()}")

            # Extract blood info
            blood_lines = [line for line in doc.split('\n') if 'Blood:' in line]
            if blood_lines:
                output.append(f"🩸 {blood_lines[0].strip()}")

            # Extract specialties
            spec_lines = [line for line in doc.split('\n') if 'Specialties:' in line]
            if spec_lines:
                output.append(f"🔬 {spec_lines[0].strip()}")

    if doctor_results and doctor_results['documents'] and doctor_results['documents'][0]:
        output.append("\n👨‍⚕️ **AVAILABLE DOCTORS:**")
        for i, doc in enumerate(doctor_results['documents'][0][:3]):  # Show top 3
            metadata = doctor_results['metadatas'][0][i]
            if metadata.get('available', False):
                output.append(f"\n**{metadata['name']}**")
                output.append(f"🔬 Specialty: {metadata['specialty']}")
                output.append(f"🏥 Hospital: {metadata['hospital']}")
                if metadata.get('experience'):
                    output.append(f"⭐ {metadata['experience']} years experience")

    return "\n".join(output)

# ==============================
# STEP 8: CHAT FUNCTION
# ==============================
def process_emergency_query(message, history):
    """Process user query and return response"""

    # Search for relevant hospitals and doctors
    hospital_results = search_hospitals(message)
    doctor_results = search_doctors(message)

    # Generate response using LLM
    response = llm.generate_response(message, hospital_results, doctor_results)

    # Also show formatted results for clarity
    formatted_results = format_results_for_display(hospital_results, doctor_results)

    # Combine responses
    full_response = f"{response}\n\n---\n{formatted_results}"

    return full_response

# ==============================
# STEP 9: GRADIO INTERFACE
# ==============================
# Create custom CSS
custom_css = """
.gr-chatbot {
    border-radius: 15px;
    box-shadow: 0 4px 6px rgba(0,0,0,0.1);
}
.message {
    padding: 15px;
    margin: 10px;
    border-radius: 15px;
    font-size: 16px;
}
.user-message {
    background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
    color: white;
}
.bot-message {
    background: linear-gradient(135deg, #f5f7fa 0%, #c3cfe2 100%);
    border: 1px solid #e0e0e0;
}
"""

# Create the interface
with gr.Blocks(theme=gr.themes.Soft(), css=custom_css) as demo:
    gr.Markdown("""
    # 🚑 Emergency Hospital Dispatcher with RAG
    ### AI-powered emergency resource finder using your hospital data

    **How to use:** Describe your emergency situation and I'll find relevant hospitals and doctors from your database.
    """)

    with gr.Row():
        with gr.Column(scale=3):
            chatbot = gr.Chatbot(
                label="Emergency Dispatch",
                height=600,
                bubble_full_width=False,
                show_label=False
            )

            with gr.Row():
                msg = gr.Textbox(
                    label="Your Message",
                    placeholder="Describe the emergency... e.g., 'Need ICU bed and surgeon for accident victim'",
                    scale=4,
                    lines=2
                )
                submit = gr.Button("🚑 Send", variant="primary", scale=1)

            with gr.Row():
                clear = gr.Button("Clear Chat", variant="secondary")
                examples = gr.Examples(
                    examples=[
                        ["Need ICU bed and surgeon for accident victim"],
                        ["Wife going into labor, need NICU and gynecologist"],
                        ["Father having chest pain, need cardiologist"],
                        ["Child with fever needs pediatrician"],
                        ["Need O+ blood for emergency surgery"],
                        ["Stroke patient needs neurologist and ICU"]
                    ],
                    inputs=[msg]
                )

    # Add status indicator
    status = gr.Markdown("✅ System Ready - Using your hospital database")

    def respond(message, chat_history):
        if not message:
            return "", chat_history

        bot_message = process_emergency_query(message, chat_history)
        chat_history.append((message, bot_message))
        return "", chat_history

    msg.submit(respond, [msg, chatbot], [msg, chatbot])
    submit.click(respond, [msg, chatbot], [msg, chatbot])
    clear.click(lambda: None, None, chatbot, queue=False)

# ==============================
# STEP 10: LAUNCH APP
# ==============================
print("\n" + "="*60)
print("🚀 Starting RAG-powered Emergency Dispatcher...")
print("📊 Database ready with:")
print(f"   - {hospital_collection.count()} hospitals")
print(f"   - {doctor_collection.count()} doctors")
print("="*60)

demo.launch(share=True, debug=False)

"""### STEP 1: Install Required Packages

First, we'll install all the necessary Python libraries for this project. This includes `langchain`, `langchain-core`, `langgraph`, `gradio`, `pandas`, `huggingface-hub`, `chromadb`, and `sentence-transformers`.
"""

# ==============================
# STEP 1: Install Required Packages (if not already installed)
# ==============================
!pip install langchain langchain-core langgraph gradio pandas huggingface-hub chromadb sentence-transformers

"""### STEP 2: Import Libraries

Next, we'll import all the required modules and classes from the installed libraries. These imports are crucial for data manipulation, building the LangGraph agent, interacting with Hugging Face models, setting up the Gradio interface, and managing the vector database.
"""

# ==============================
# STEP 2: Import Libraries
# ==============================
import pandas as pd
import os
import gradio as gr
from typing import Annotated, TypedDict, Optional, List
from langchain_core.messages import BaseMessage, HumanMessage, SystemMessage, AIMessage
from langgraph.graph import StateGraph, START, END
from langgraph.graph.message import add_messages
from huggingface_hub import InferenceClient
from google.colab import userdata
import chromadb
from chromadb.utils import embedding_functions

"""### STEP 3: Setup Hugging Face API Token

This step handles authentication with Hugging Face. It attempts to retrieve an API token from Colab secrets. If not found, it prompts the user to enter it. This token is essential for accessing models via the `huggingface_hub.InferenceClient`.
"""

# ==============================
# STEP 3: SETUP HUGGING FACE API
# ==============================
try:
    HF_TOKEN = userdata.get('HF_TOKEN')
    if HF_TOKEN:
        print("✅ Using HF_TOKEN from Colab secrets")
    else:
        raise ValueError("HF_TOKEN not found in secrets")
except:
    HF_TOKEN = input("Enter your Hugging Face token: ").strip()
    if not HF_TOKEN:
        raise ValueError("HF_TOKEN is required")

os.environ["HF_TOKEN"] = HF_TOKEN

"""### STEP 4: Load Your CSV Files

Here, you will be prompted to upload two CSV files: one for hospital data and another for doctor data. These files will be loaded into pandas DataFrames, which will then be used to populate the vector database.
"""

# ==============================
# STEP 4: LOAD YOUR CSV FILES
# ==============================
from google.colab import files

print("\n📁 Please upload your hospital CSV file:")
uploaded_hospitals = files.upload()
hospital_filename = list(uploaded_hospitals.keys())[0]
hospitals_df = pd.read_csv(hospital_filename)

print("\n📁 Please upload your doctor CSV file:")
uploaded_doctors = files.upload()
doctor_filename = list(uploaded_doctors.keys())[0]
doctors_df = pd.read_csv(doctor_filename)

print(f"\n✅ Loaded {len(hospitals_df)} hospitals")
print(f"✅ Loaded {len(doctors_df)} doctors")

"""### STEP 5: Setup Vector Database (ChromaDB)

This section initializes ChromaDB, sets up an embedding function using `sentence-transformers`, and creates two collections: one for hospitals and one for doctors. It then populates these collections with data from your uploaded CSV files if they are empty, converting the structured data into searchable vector embeddings.
"""

# ==============================
# STEP 5: SETUP VECTOR DATABASE
# ==============================
print("\n🔧 Setting up vector database...")

# Initialize ChromaDB
chroma_client = chromadb.Client()

# Use sentence-transformers for embeddings
sentence_transformer_ef = embedding_functions.SentenceTransformerEmbeddingFunction(
    model_name="all-MiniLM-L6-v2"
)

# Create or get collections
try:
    hospital_collection = chroma_client.get_collection(
        name="hospitals",
        embedding_function=sentence_transformer_ef
    )
    print("✅ Using existing hospital collection")
except:
    hospital_collection = chroma_client.create_collection(
        name="hospitals",
        embedding_function=sentence_transformer_ef
    )
    print("✅ Created new hospital collection")

try:
    doctor_collection = chroma_client.get_collection(
        name="doctors",
        embedding_function=sentence_transformer_ef
    )
    print("✅ Using existing doctor collection")
except:
    doctor_collection = chroma_client.create_collection(
        name="doctors",
        embedding_function=sentence_transformer_ef
    )
    print("✅ Created new doctor collection")

# Check if collections have data
if hospital_collection.count() == 0:
    print("📊 Adding hospitals to vector database...")
    hospital_docs = []
    hospital_metadata = []
    hospital_ids = []

    for idx, row in hospitals_df.iterrows():
        # Create bed info
        bed_info = []
        for col in ['ICU_Beds', 'General_Ward_Beds', 'NICU_Beds', 'Women_Ward_Beds', 'Deluxe_Ward_Beds']:
            if col in hospitals_df.columns and pd.notna(row.get(col)) and row.get(col, 0) > 0:
                bed_info.append(f"{col}: {row[col]} beds")

        # Create blood info
        blood_info = []
        for blood in ['A+', 'A-', 'B+', 'B-', 'AB+', 'AB-', 'O+', 'O-']:
            if blood in hospitals_df.columns and pd.notna(row.get(blood)) and row.get(blood, 0) > 0:
                blood_info.append(f"{blood}: {row[blood]} units")

        doc = f"""
Hospital: {row['Name']}
Address: {row['Address']}
Contact: {row['Contact']}

Available Beds:
{chr(10).join(bed_info) if bed_info else 'No beds currently available'}

Available Blood:
{chr(10).join(blood_info) if blood_info else 'No blood currently available'}

Specialties: {row.get('Available_Specialties', 'Not specified')}
"""
        hospital_docs.append(doc)
        hospital_metadata.append({
            "name": row['Name'],
            "address": row['Address'],
            "contact": row['Contact'],
            "type": "hospital"
        })
        hospital_ids.append(f"hospital_{idx}")

    hospital_collection.add(
        documents=hospital_docs,
        metadatas=hospital_metadata,
        ids=hospital_ids
    )
    print(f"✅ Added {len(hospital_docs)} hospitals")

if doctor_collection.count() == 0:
    print("📊 Adding doctors to vector database...")
    doctor_docs = []
    doctor_metadata = []
    doctor_ids = []

    for idx, row in doctors_df.iterrows():
        # Find hospital name
        hospital_name = "Unknown"
        if 'Hospital_ID' in row and pd.notna(row['Hospital_ID']):
            hospital_match = hospitals_df[hospitals_df['Hospital_ID'] == row['Hospital_ID']]
            if not hospital_match.empty:
                hospital_name = hospital_match.iloc[0]['Name']

        doctor_name = row.get('Name', row.get('Name_x', f'Dr. {idx}'))

        doc = f"""
Doctor: {doctor_name}
Specialty: {row['Specialty']}
Hospital: {hospital_name}
Status: {'Available' if row.get('Is_Available', False) else 'Not Available'}
On Call: {'Yes' if row.get('On_Call_Emergency', False) else 'No'}
Experience: {row.get('Experience_Years', 'Unknown')} years
"""
        doctor_docs.append(doc)
        doctor_metadata.append({
            "name": doctor_name,
            "specialty": row['Specialty'],
            "hospital": hospital_name,
            "available": bool(row.get('Is_Available', False)),
            "on_call": bool(row.get('On_Call_Emergency', False)),
            "experience": row.get('Experience_Years', 0),
            "type": "doctor"
        })
        doctor_ids.append(f"doctor_{idx}")

    doctor_collection.add(
        documents=doctor_docs,
        metadatas=doctor_metadata,
        ids=doctor_ids
    )
    print(f"✅ Added {len(doctor_docs)} doctors")

print(f"\n📊 Database stats: {hospital_collection.count()} hospitals, {doctor_collection.count()} doctors")

"""### STEP 6: Hugging Face LLM Setup

This defines the `EmergencyDispatcherLLM` class, which uses the Hugging Face `InferenceClient` to generate responses. It constructs a detailed prompt using the retrieved RAG results (hospitals and doctors) and provides a fallback mechanism if the LLM call fails. The LLM is then initialized.
"""

# ==============================
# STEP 6: HUGGING FACE LLM SETUP
# ==============================
class EmergencyDispatcherLLM:
    def __init__(self, model_id="microsoft/Phi-3-mini-4k-instruct", token=HF_TOKEN):
        self.client = InferenceClient(model=model_id, token=token)

    def generate_response(self, query, hospital_results, doctor_results):
        """Generate response using RAG results"""

        # Format hospital results
        hospital_text = "=== AVAILABLE HOSPITALS ===\n"
        if hospital_results and 'documents' in hospital_results and hospital_results['documents'][0]:
            for i, doc in enumerate(hospital_results['documents'][0]):
                metadata = hospital_results['metadatas'][0][i]
                hospital_text += f"\n🏥 {metadata['name']}\n"
                hospital_text += f"📍 {metadata['address']}\n"
                hospital_text += f"📞 {metadata['contact']}\n"
                # Extract key info from document
                doc_lines = doc.split('\n')
                for line in doc_lines:
                    if 'Beds:' in line or 'Blood:' in line or 'Specialties:' in line:
                        hospital_text += f"   {line.strip()}\n"
        else:
            hospital_text += "No matching hospitals found.\n"

        # Format doctor results
        doctor_text = "\n=== AVAILABLE DOCTORS ===\n"
        if doctor_results and 'documents' in doctor_results and doctor_results['documents'][0]:
            for i, doc in enumerate(doctor_results['documents'][0]):
                metadata = doctor_results['metadatas'][0][i]
                if metadata.get('available', False):  # Only show available doctors
                    doctor_text += f"\n👨‍⚕️ {metadata['name']}\n"
                    doctor_text += f"   Specialty: {metadata['specialty']}\n"
                    doctor_text += f"   Hospital: {metadata['hospital']}\n"
                    if metadata.get('experience'):
                        doctor_text += f"   Experience: {metadata['experience']} years\n"
        else:
            doctor_text += "No available doctors found.\n"

        # Create prompt for LLM
        prompt = f"""<|system|>
You are an Emergency Hospital Dispatcher AI. Your role is to help people find emergency medical services quickly and accurately.

Based on the search results below, provide a helpful response to the user's emergency query. Format your response clearly and include:
- Hospital names, addresses, and contact numbers
- Types of beds available
- Available doctors with their specialties
- Blood availability if relevant

Keep responses concise but include all critical information for an emergency.
and give only info about what they ask not other than this
<|end|>
<|user|>
Emergency Query: {query}

Search Results:
{hospital_text}
{doctor_text}
<|end|>
<|assistant|>"""

        try:
            response = self.client.text_generation(
                prompt,
                max_new_tokens=800,
                temperature=0.1,
                do_sample=True,
                return_full_text=False
            )
            return response
        except Exception as e:
            print(f"Error calling Hugging Face: {e}")
            return self._generate_fallback_response(hospital_text, doctor_text)

    def _generate_fallback_response(self, hospital_text, doctor_text):
        """Generate a simple response if LLM fails"""
        response = "Here are the available emergency resources I found:\n\n"
        response += hospital_text
        response += doctor_text
        return response

# Initialize LLM
llm = EmergencyDispatcherLLM()

# ==============================
# STEP 6: HUGGING FACE LLM SETUP
# ==============================
class EmergencyDispatcherLLM:
    def __init__(self, model_id="microsoft/Phi-3-mini-4k-instruct", token=HF_TOKEN):
        self.client = InferenceClient(model=model_id, token=token)

    def generate_response(self, query, hospital_results, doctor_results):
        """Generate response using RAG results"""

        # Format hospital results
        hospital_text = "=== AVAILABLE HOSPITALS ===\n"
        if hospital_results and 'documents' in hospital_results and hospital_results['documents'][0]:
            for i, doc in enumerate(hospital_results['documents'][0]):
                metadata = hospital_results['metadatas'][0][i]
                hospital_text += f"\n🏥 {metadata['name']}\n"
                hospital_text += f"📍 {metadata['address']}\n"
                hospital_text += f"📞 {metadata['contact']}\n"
                # Extract key info from document
                doc_lines = doc.split('\n')
                for line in doc_lines:
                    if 'Beds:' in line or 'Blood:' in line or 'Specialties:' in line:
                        hospital_text += f"   {line.strip()}\n"
        else:
            hospital_text += "No matching hospitals found.\n"

        # Format doctor results
        doctor_text = "\n=== AVAILABLE DOCTORS ===\n"
        if doctor_results and 'documents' in doctor_results and doctor_results['documents'][0]:
            for i, doc in enumerate(doctor_results['documents'][0]):
                metadata = doctor_results['metadatas'][0][i]
                if metadata.get('available', False):  # Only show available doctors
                    doctor_text += f"\n👨‍⚕️ {metadata['name']}\n"
                    doctor_text += f"   Specialty: {metadata['specialty']}\n"
                    doctor_text += f"   Hospital: {metadata['hospital']}\n"
                    if metadata.get('experience'):
                        doctor_text += f"   Experience: {metadata['experience']} years\n"
        else:
            doctor_text += "No available doctors found.\n"

        # Create prompt for LLM
        prompt = f"""<|system|>
You are an Emergency Hospital Dispatcher AI. Your role is to help people find emergency medical services quickly and accurately.

Based ONLY on the search results below, provide a helpful response to the user's emergency query. If information for a specific request (e.g., specific bed type, blood type, or doctor specialty) is NOT found in the search results, explicitly state that it is unavailable.

Format your response clearly using Markdown.
- Use **bold** for names and important details.
- Use bullet points for lists of information (e.g., beds, blood types, specialties).
- Start with a clear summary of findings.
- If hospitals or doctors are found, provide their details in separate sections using Markdown headings (e.g., `### Hospitals`, `### Doctors`).
- Include:
    - Hospital names, addresses, and contact numbers.
    - Specific types of beds available (only if specified and found).
    - Available doctors with their specialties, hospital, and experience (only if specified and found).
    - Blood availability (only if specified and found).

Prioritize factual information from the search results. Keep responses concise but include all critical information for an emergency. Do not include any information that is not present in the search results.
<|end|>
<|user|>
Emergency Query: {query}

Search Results:
{hospital_text}
{doctor_text}
<|end|>
<|assistant|>"""

        try:
            response = self.client.text_generation(
                prompt,
                max_new_tokens=800,
                temperature=0.1,
                do_sample=True,
                return_full_text=False
            )
            return response
        except Exception as e:
            print(f"Error calling Hugging Face: {e}")
            return self._generate_fallback_response(hospital_text, doctor_text)

    def _generate_fallback_response(self, hospital_text, doctor_text):
        """Generate a simple response if LLM fails"""
        response = "Here are the available emergency resources I found:\n\n"
        response += hospital_text
        response += doctor_text
        return response

# Initialize LLM
llm = EmergencyDispatcherLLM()

"""### STEP 7: Search Functions

These functions are responsible for querying the ChromaDB collections. `search_hospitals` and `search_doctors` perform semantic searches based on the user's query. `format_results_for_display` then takes these raw search results and structures them into a human-readable format for presentation.
"""

# ==============================
# STEP 7: SEARCH FUNCTIONS
# ==============================
def search_hospitals(query: str, n_results: int = 5):
    """Search hospitals using semantic search"""
    try:
        results = hospital_collection.query(
            query_texts=[query],
            n_results=n_results
        )
        return results
    except Exception as e:
        print(f"Error searching hospitals: {e}")
        return None

def search_doctors(query: str, n_results: int = 5):
    """Search doctors using semantic search"""
    try:
        results = doctor_collection.query(
            query_texts=[query],
            n_results=n_results
        )
        return results
    except Exception as e:
        print(f"Error searching doctors: {e}")
        return None

def format_results_for_display(hospital_results, doctor_results):
    """Format search results for display"""
    output = []

    if hospital_results and hospital_results['documents'] and hospital_results['documents'][0]:
        output.append("🏥 **HOSPITALS WITH RESOURCES:**")
        for i, doc in enumerate(hospital_results['documents'][0][:3]):  # Show top 3
            metadata = hospital_results['metadatas'][0][i]
            output.append(f"\n**{metadata['name']}**")
            output.append(f"📍 {metadata['address']}")
            output.append(f"📞 {metadata['contact']}")

            # Extract bed info
            bed_lines = [line for line in doc.split('\n') if 'Beds:' in line]
            if bed_lines:
                output.append(f"🛏️ {bed_lines[0].strip()}")

            # Extract blood info
            blood_lines = [line for line in doc.split('\n') if 'Blood:' in line]
            if blood_lines:
                output.append(f"🩸 {blood_lines[0].strip()}")

            # Extract specialties
            spec_lines = [line for line in doc.split('\n') if 'Specialties:' in line]
            if spec_lines:
                output.append(f"🔬 {spec_lines[0].strip()}")

    if doctor_results and doctor_results['documents'] and doctor_results['documents'][0]:
        output.append("\n👨‍⚕️ **AVAILABLE DOCTORS:**")
        for i, doc in enumerate(doctor_results['documents'][0][:3]):  # Show top 3
            metadata = doctor_results['metadatas'][0][i]
            if metadata.get('available', False):
                output.append(f"\n**{metadata['name']}**")
                output.append(f"🔬 Specialty: {metadata['specialty']}")
                output.append(f"🏥 Hospital: {metadata['hospital']}")
                if metadata.get('experience'):
                    output.append(f"⭐ {metadata['experience']} years experience")

    return "\n".join(output)

"""### STEP 8: Chat Function (`process_emergency_query`)

This function orchestrates the entire query process. It takes a user's emergency message, performs semantic searches for hospitals and doctors, uses the LLM to generate a coherent response based on these search results, and then combines the LLM's output with a clearly formatted display of the top search results.
"""

# ==============================
# STEP 8: CHAT FUNCTION
# ==============================
def process_emergency_query(message, history):
    """Process user query and return response"""

    # Search for relevant hospitals and doctors
    hospital_results = search_hospitals(message)
    doctor_results = search_doctors(message)

    # Generate response using LLM
    response = llm.generate_response(message, hospital_results, doctor_results)

    # Also show formatted results for clarity
    formatted_results = format_results_for_display(hospital_results, doctor_results)

    # Combine responses
    full_response = f"{response}\n\n---\n{formatted_results}"

    return full_response

"""### STEP 9: Gradio Interface and App Launch

Finally, this section sets up the interactive Gradio user interface. It defines the chatbot, input textbox, submit and clear buttons, and provides example queries. The `respond` function links the Gradio components to our `process_emergency_query` function. The app is then launched, making it accessible via a shareable link.
"""

# ==============================
# STEP 9: GRADIO INTERFACE
# ==============================
# Create custom CSS
custom_css = """
.gr-chatbot {
    border-radius: 15px;
    box-shadow: 0 4px 6px rgba(0,0,0,0.1);
}
.message {
    padding: 15px;
    margin: 10px;
    border-radius: 15px;
    font-size: 16px;
}
.user-message {
    background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
    color: white;
}
.bot-message {
    background: linear-gradient(135deg, #f5f7fa 0%, #c3cfe2 100%);
    border: 1px solid #e0e0e0;
}
"""

# Create the interface
with gr.Blocks(theme=gr.themes.Soft(), css=custom_css) as demo:
    gr.Markdown("""
    # 🚑 Emergency Hospital Dispatcher with RAG
    ### AI-powered emergency resource finder using your hospital data

    **How to use:** Describe your emergency situation and I'll find relevant hospitals and doctors from your database.
    """)

    with gr.Row():
        with gr.Column(scale=3):
            chatbot = gr.Chatbot(
                label="Emergency Dispatch",
                height=600,
                bubble_full_width=False,
                show_label=False
            )

            with gr.Row():
                msg = gr.Textbox(
                    label="Your Message",
                    placeholder="Describe the emergency... e.g., 'Need ICU bed and surgeon for accident victim'",
                    scale=4,
                    lines=2
                )
                submit = gr.Button("🚑 Send", variant="primary", scale=1)

            with gr.Row():
                clear = gr.Button("Clear Chat", variant="secondary")
                examples = gr.Examples(
                    examples=[
                        ["Need ICU bed and surgeon for accident victim"],
                        ["Wife going into labor, need NICU and gynecologist"],
                        ["Father having chest pain, need cardiologist"],
                        ["Child with fever needs pediatrician"],
                        ["Need O+ blood for emergency surgery"],
                        ["Stroke patient needs neurologist and ICU"]
                    ],
                    inputs=[msg]
                )

    # Add status indicator
    status = gr.Markdown("✅ System Ready - Using your hospital database")

    def respond(message, chat_history):
        if not message:
            return "", chat_history

        bot_message = process_emergency_query(message, chat_history)
        chat_history.append((message, bot_message))
        return "", chat_history

    msg.submit(respond, [msg, chatbot], [msg, chatbot])
    submit.click(respond, [msg, chatbot], [msg, chatbot])
    clear.click(lambda: None, None, chatbot, queue=False)

# ==============================
# STEP 10: LAUNCH APP
# ==============================
print("\n" + "="*60)
print("🚀 Starting RAG-powered Emergency Dispatcher...")
print(f"📊 Database ready with:")
print(f"   - {hospital_collection.count()} hospitals")
print(f"   - {doctor_collection.count()} doctors")
print("="*60)

demo.launch(share=True, debug=False)

def is_structured_query(query: str) -> bool:
    keywords = [
        "how many", "count", "maximum", "minimum",
        "most", "least", "available", "number of",
        "which hospital has", "total"
    ]
    query_lower = query.lower()
    return any(k in query_lower for k in keywords)

def pandas_answer(query, hospitals_df, doctors_df):
    q = query.lower()

    # ICU beds
    if "icu" in q and ("most" in q or "maximum" in q):
        result = hospitals_df.loc[
            hospitals_df['ICU_Beds'].idxmax()
        ]
        return f"""
🏥 Hospital with most ICU beds:
Name: {result['Name']}
ICU Beds: {int(result['ICU_Beds'])}
Address: {result['Address']}
Contact: {result['Contact']}
"""

    # Available doctors count
    if "how many" in q and "doctors" in q:
        count = doctors_df[doctors_df['Is_Available'] == True].shape[0]
        return f"👨‍⚕️ Total available doctors right now: {count}"

    # Blood availability
    for blood in ['A+', 'A-', 'B+', 'B-', 'AB+', 'AB-', 'O+', 'O-']:
        if blood.lower() in q:
            available = hospitals_df[hospitals_df[blood] > 0]
            if available.empty:
                return f"🩸 No hospitals currently have {blood} blood available."
            return "\n".join(
                f"🏥 {row['Name']} – {int(row[blood])} units"
                for _, row in available.iterrows()
            )

    return None

def process_emergency_query(message, history):
    # FIRST: try Pandas for correctness
    if is_structured_query(message):
        pandas_result = pandas_answer(message, hospitals_df, doctors_df)
        if pandas_result:
            return pandas_result

    # FALLBACK: RAG (your existing logic)
    hospital_results = search_hospitals(message)
    doctor_results = search_doctors(message)

    response = llm.generate_response(message, hospital_results, doctor_results)
    formatted_results = format_results_for_display(hospital_results, doctor_results)

    return f"{response}\n\n---\n{formatted_results}"

hospitals_df.columns = hospitals_df.columns.str.strip()
doctors_df.columns = doctors_df.columns.str.strip()

hospitals_df['ICU_Beds'] = pd.to_numeric(
    hospitals_df['ICU_Beds'], errors='coerce'
).fillna(0)

hospitals_df['Hospital_ID'] = hospitals_df['Hospital_ID'].astype(str)
doctors_df['Hospital_ID'] = doctors_df['Hospital_ID'].astype(str)

print(hospitals_df[['Name', 'ICU_Beds']].sort_values('ICU_Beds', ascending=False).head())

