# Generated by Django 3.2.25 on 2026-02-17 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0003_auto_20260218_0512'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambulance',
            name='location',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='ambulance',
            name='status',
            field=models.CharField(default='Available', max_length=20),
        ),
    ]
