# Generated by Django 5.2.11 on 2026-02-18 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0008_doctor_on_shift_hospital_closing_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='on_call',
            field=models.BooleanField(default=False),
        ),
    ]
