# Generated by Django 5.2.11 on 2026-02-18 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0009_doctor_on_call'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='shift_timings',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
