# Generated by Django 5.2.11 on 2026-02-18 03:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0010_doctor_phone_doctor_shift_timings'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=255)),
                ('patient_condition', models.CharField(max_length=255)),
                ('severity', models.CharField(choices=[('Critical', 'Critical'), ('Moderate', 'Moderate'), ('Stable', 'Stable')], default='Moderate', max_length=20)),
                ('eta_minutes', models.IntegerField(default=10)),
                ('distance_km', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Enroute', 'Enroute'), ('Arrived', 'Arrived'), ('HandedOver', 'HandedOver')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ambulance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergencies', to='hospitals.ambulance')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergencies', to='hospitals.hospital')),
            ],
        ),
    ]
